// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.Ledger;

#nullable disable

namespace Poyra.Modules.Ledger.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260805145041_HesapEkstresiMutabakati")]
    partial class HesapEkstresiMutabakati
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.Ledger.Domain.BankReceivable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttemptPublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attempt_public_id");

                    b.Property<DateTimeOffset?>("BankConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bank_confirmed_at");

                    b.Property<DateTimeOffset>("CapturedAtServer")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_server");

                    b.Property<long?>("ConfirmedCommissionMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_commission_minor");

                    b.Property<long?>("ConfirmedNetMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_net_minor");

                    b.Property<DateOnly?>("ConfirmedValueDate")
                        .HasColumnType("date")
                        .HasColumnName("confirmed_value_date");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long?>("ExpectedCommissionMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_commission_minor");

                    b.Property<long?>("ExpectedNetMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_net_minor");

                    b.Property<int?>("ExpectedRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("expected_rate_bps");

                    b.Property<DateOnly?>("ExpectedValueDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_value_date");

                    b.Property<long>("GrossMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_minor");

                    b.Property<int>("Installments")
                        .HasColumnType("integer")
                        .HasColumnName("installments");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("PaymentPublicId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_public_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'rcv_' || replace(id::text, '-', '')", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bank_receivables");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_receivables_public_id");

                    b.HasIndex("TenantId", "ConnectorAccountId")
                        .HasDatabaseName("ix_bank_receivables_tenant_id_connector_account_id");

                    b.HasIndex("TenantId", "AttemptPublicId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_receivables_tenant_id_attempt_public_id_kind");

                    b.HasIndex("TenantId", "Status", "ExpectedValueDate")
                        .HasDatabaseName("ix_bank_receivables_tenant_id_status_expected_value_date");

                    b.ToTable("bank_receivables", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Ledger.Domain.SettlementFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ActualMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_minor");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DeltaMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("delta_minor");

                    b.Property<long>("ExpectedMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_minor");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<int>("ReceivableCount")
                        .HasColumnType("integer")
                        .HasColumnName("receivable_count");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id")
                        .HasName("pk_settlement_findings");

                    b.HasIndex("StatementId")
                        .HasDatabaseName("ix_settlement_findings_statement_id");

                    b.HasIndex("TenantId", "Outcome", "ValueDate")
                        .HasDatabaseName("ix_settlement_findings_tenant_id_outcome_value_date");

                    b.HasIndex("TenantId", "StatementId", "ValueDate")
                        .IsUnique()
                        .HasDatabaseName("ix_settlement_findings_tenant_id_statement_id_value_date");

                    b.ToTable("settlement_findings", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Ledger.Domain.SettlementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reference");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id")
                        .HasName("pk_settlement_lines");

                    b.HasIndex("StatementId")
                        .HasDatabaseName("ix_settlement_lines_statement_id");

                    b.HasIndex("TenantId", "StatementId", "ValueDate")
                        .HasDatabaseName("ix_settlement_lines_tenant_id_statement_id_value_date");

                    b.ToTable("settlement_lines", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Ledger.Domain.SettlementStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer")
                        .HasColumnName("line_count");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'set_' || replace(id::text, '-', '')", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_settlement_statements");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_settlement_statements_public_id");

                    b.HasIndex("TenantId", "ConnectorAccountId")
                        .HasDatabaseName("ix_settlement_statements_tenant_id_connector_account_id");

                    b.ToTable("settlement_statements", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Ledger.Domain.SettlementFinding", b =>
                {
                    b.HasOne("Poyra.Modules.Ledger.Domain.SettlementStatement", null)
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlement_findings_settlement_statements_statement_id");
                });

            modelBuilder.Entity("Poyra.Modules.Ledger.Domain.SettlementLine", b =>
                {
                    b.HasOne("Poyra.Modules.Ledger.Domain.SettlementStatement", null)
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlement_lines_settlement_statements_statement_id");
                });
#pragma warning restore 612, 618
        }
    }
}
