// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.Ledger;

#nullable disable

namespace Poyra.Modules.Ledger.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260805134329_BankadanAlacak")]
    partial class BankadanAlacak
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.Ledger.Domain.BankReceivable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttemptPublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attempt_public_id");

                    b.Property<DateTimeOffset?>("BankConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bank_confirmed_at");

                    b.Property<DateTimeOffset>("CapturedAtServer")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_server");

                    b.Property<long?>("ConfirmedCommissionMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_commission_minor");

                    b.Property<long?>("ConfirmedNetMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_net_minor");

                    b.Property<DateOnly?>("ConfirmedValueDate")
                        .HasColumnType("date")
                        .HasColumnName("confirmed_value_date");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long?>("ExpectedCommissionMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_commission_minor");

                    b.Property<long?>("ExpectedNetMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_net_minor");

                    b.Property<int?>("ExpectedRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("expected_rate_bps");

                    b.Property<DateOnly?>("ExpectedValueDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_value_date");

                    b.Property<long>("GrossMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_minor");

                    b.Property<int>("Installments")
                        .HasColumnType("integer")
                        .HasColumnName("installments");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("PaymentPublicId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_public_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'rcv_' || replace(id::text, '-', '')", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bank_receivables");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_receivables_public_id");

                    b.HasIndex("TenantId", "ConnectorAccountId")
                        .HasDatabaseName("ix_bank_receivables_tenant_id_connector_account_id");

                    b.HasIndex("TenantId", "AttemptPublicId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_receivables_tenant_id_attempt_public_id_kind");

                    b.HasIndex("TenantId", "Status", "ExpectedValueDate")
                        .HasDatabaseName("ix_bank_receivables_tenant_id_status_expected_value_date");

                    b.ToTable("bank_receivables", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
