// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.Vault;

#nullable disable

namespace Poyra.Modules.Vault.Migrations
{
    [DbContext(typeof(VaultDbContext))]
    partial class VaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.Vault.Domain.CardToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("brand");

                    b.Property<byte[]>("CardEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("card_encrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_ref");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("integer")
                        .HasColumnName("expiry_month");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("integer")
                        .HasColumnName("expiry_year");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("masked_pan");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_token")
                        .HasComputedColumnSql("'tok_' || replace(id::text, '-', '')", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_card_tokens");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasDatabaseName("ix_card_tokens_public_token");

                    b.HasIndex("TenantId", "CustomerRef")
                        .HasDatabaseName("ix_card_tokens_tenant_id_customer_ref");

                    b.HasIndex("TenantId", "CustomerRef", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_card_tokens_tenant_id_customer_ref_fingerprint")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("card_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_card_tokens_expiry_month", "expiry_month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_card_tokens_expiry_year", "expiry_year BETWEEN 2000 AND 2099");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
