// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.Recon;

#nullable disable

namespace Poyra.Modules.Recon.Migrations
{
    [DbContext(typeof(ReconDbContext))]
    [Migration("20260801172706_ReconDeepening")]
    partial class ReconDeepening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.Recon.Domain.CommissionAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("installment_count");

                    b.Property<int>("RateBps")
                        .HasColumnType("integer")
                        .HasColumnName("rate_bps");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ValorDays")
                        .HasColumnType("integer")
                        .HasColumnName("valor_days");

                    b.HasKey("Id")
                        .HasName("pk_commission_agreements");

                    b.HasIndex("TenantId", "ConnectorAccountId", "InstallmentCount")
                        .IsUnique()
                        .HasDatabaseName("ix_commission_agreements_tenant_id_connector_account_id_instal");

                    b.ToTable("commission_agreements", null, t =>
                        {
                            t.HasCheckConstraint("ck_commission_agreements_count", "installment_count BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_commission_agreements_rate", "rate_bps BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("Poyra.Modules.Recon.Domain.CommissionAuditFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ActualCommissionMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_commission_minor");

                    b.Property<int?>("AgreedRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("agreed_rate_bps");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DeltaMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("delta_minor");

                    b.Property<long?>("ExpectedCommissionMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_commission_minor");

                    b.Property<long>("GrossMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_minor");

                    b.Property<int>("Installments")
                        .HasColumnType("integer")
                        .HasColumnName("installments");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_id");

                    b.Property<Guid>("StatementLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_line_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_commission_audit_findings");

                    b.HasIndex("StatementId")
                        .HasDatabaseName("ix_commission_audit_findings_statement_id");

                    b.HasIndex("StatementLineId")
                        .HasDatabaseName("ix_commission_audit_findings_statement_line_id");

                    b.HasIndex("TenantId", "StatementId")
                        .HasDatabaseName("ix_commission_audit_findings_tenant_id_statement_id");

                    b.ToTable("commission_audit_findings", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Recon.Domain.ReconStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountMismatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("amount_mismatch_count");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer")
                        .HasColumnName("line_count");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<int>("MissingInPoyraCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_in_poyra_count");

                    b.Property<int>("MissingInStatementCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_in_statement_count");

                    b.Property<int>("RefundLineCount")
                        .HasColumnType("integer")
                        .HasColumnName("refund_line_count");

                    b.Property<DateOnly>("StatementDate")
                        .HasColumnType("date")
                        .HasColumnName("statement_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recon_statements");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_recon_statements_status")
                        .HasFilter("status = 'matching'");

                    b.HasIndex("TenantId", "ConnectorAccountId", "StatementDate")
                        .HasDatabaseName("ix_recon_statements_tenant_id_connector_account_id_statement_d");

                    b.ToTable("recon_statements", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Recon.Domain.ReconStatementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CommissionMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("commission_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpectedValueDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_value_date");

                    b.Property<long>("GrossMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_minor");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("line_type");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("match_status");

                    b.Property<Guid?>("MatchedAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_attempt_id");

                    b.Property<Guid?>("MatchedRefundId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_refund_id");

                    b.Property<long>("NetMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("net_minor");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_id");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("ValorDeltaDays")
                        .HasColumnType("integer")
                        .HasColumnName("valor_delta_days");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id")
                        .HasName("pk_recon_statement_lines");

                    b.HasIndex("StatementId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_recon_statement_lines_statement_id_line_no");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_recon_statement_lines_tenant_id_order_id");

                    b.ToTable("recon_statement_lines", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Recon.Domain.CommissionAuditFinding", b =>
                {
                    b.HasOne("Poyra.Modules.Recon.Domain.ReconStatement", null)
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commission_audit_findings_recon_statements_statement_id");

                    b.HasOne("Poyra.Modules.Recon.Domain.ReconStatementLine", null)
                        .WithMany()
                        .HasForeignKey("StatementLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commission_audit_findings_recon_statement_lines_statement_l");
                });

            modelBuilder.Entity("Poyra.Modules.Recon.Domain.ReconStatementLine", b =>
                {
                    b.HasOne("Poyra.Modules.Recon.Domain.ReconStatement", null)
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recon_statement_lines_recon_statements_statement_id");
                });
#pragma warning restore 612, 618
        }
    }
}
