// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.PaymentLinks;

#nullable disable

namespace Poyra.Modules.PaymentLinks.Migrations
{
    [DbContext(typeof(PaymentLinksDbContext))]
    [Migration("20260803062124_AddKarekodSettings")]
    partial class AddKarekodSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.PaymentLinks.Domain.KarekodSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("category_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MerchantCity")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("merchant_city");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("merchant_name");

                    b.Property<string>("MerchantNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("merchant_no");

                    b.Property<string>("SchemeGuid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scheme_guid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId")
                        .HasName("pk_karekod_settings");

                    b.ToTable("karekod_settings", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.PaymentLinks.Domain.PaymentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxInstallments")
                        .HasColumnType("integer")
                        .HasColumnName("max_installments");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("integer")
                        .HasColumnName("max_usage");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'lnk_' || replace(id::text, '-', '')", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payment_links");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_links_public_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_links_slug");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_payment_links_tenant_id_created_at");

                    b.ToTable("payment_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_links_amount", "amount_minor IS NULL OR amount_minor > 0");

                            t.HasCheckConstraint("ck_payment_links_installments", "max_installments BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_payment_links_usage", "max_usage >= 0");
                        });
                });

            modelBuilder.Entity("Poyra.Modules.PaymentLinks.Domain.PaymentLinkLookup", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_link_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Slug")
                        .HasName("pk_payment_link_lookups");

                    b.HasIndex("PaymentLinkId")
                        .HasDatabaseName("ix_payment_link_lookups_payment_link_id");

                    b.ToTable("payment_link_lookups", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.PaymentLinks.Domain.PaymentLinkUsage", b =>
                {
                    b.Property<string>("PaymentPublicId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("payment_public_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_link_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("PaymentPublicId")
                        .HasName("pk_payment_link_usages");

                    b.HasIndex("PaymentLinkId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_payment_link_usages_payment_link_id_created_at");

                    b.ToTable("payment_link_usages", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.PaymentLinks.Domain.PaymentLinkLookup", b =>
                {
                    b.HasOne("Poyra.Modules.PaymentLinks.Domain.PaymentLink", null)
                        .WithMany()
                        .HasForeignKey("PaymentLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_link_lookups_payment_links_payment_link_id");
                });

            modelBuilder.Entity("Poyra.Modules.PaymentLinks.Domain.PaymentLinkUsage", b =>
                {
                    b.HasOne("Poyra.Modules.PaymentLinks.Domain.PaymentLink", null)
                        .WithMany()
                        .HasForeignKey("PaymentLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_link_usages_payment_links_payment_link_id");
                });
#pragma warning restore 612, 618
        }
    }
}
