// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.Disputes;

#nullable disable

namespace Poyra.Modules.Disputes.Migrations
{
    [DbContext(typeof(DisputesDbContext))]
    partial class DisputesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.Disputes.Domain.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ConnectorDisputeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("connector_dispute_id");

                    b.Property<string>("ConnectorKey")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("connector_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DueWarningSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_warning_sent_at");

                    b.Property<DateTimeOffset>("EvidenceDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evidence_due_at");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("evidence_summary");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("PaymentIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_intent_id");

                    b.Property<string>("PaymentPublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_public_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'dsp_' || replace(id::text, '-', '')", true);

                    b.Property<string>("RawReasonCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("raw_reason_code");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_disputes");

                    b.HasIndex("EvidenceDueAt")
                        .HasDatabaseName("ix_disputes_evidence_due_at")
                        .HasFilter("status = 'open'");

                    b.HasIndex("PaymentIntentId")
                        .HasDatabaseName("ix_disputes_payment_intent_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_disputes_public_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_disputes_tenant_id");

                    b.HasIndex("TenantId", "ConnectorDisputeId")
                        .IsUnique()
                        .HasDatabaseName("ix_disputes_tenant_id_connector_dispute_id")
                        .HasFilter("connector_dispute_id IS NOT NULL");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Disputes.Domain.DisputeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispute_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_dispute_events");

                    b.HasIndex("DisputeId")
                        .HasDatabaseName("ix_dispute_events_dispute_id");

                    b.ToTable("dispute_events", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Disputes.Domain.DisputeEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispute_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_dispute_evidences");

                    b.HasIndex("DisputeId")
                        .HasDatabaseName("ix_dispute_evidences_dispute_id");

                    b.ToTable("dispute_evidences", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Disputes.Domain.DisputeEvent", b =>
                {
                    b.HasOne("Poyra.Modules.Disputes.Domain.Dispute", null)
                        .WithMany()
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_events_disputes_dispute_id");
                });

            modelBuilder.Entity("Poyra.Modules.Disputes.Domain.DisputeEvidence", b =>
                {
                    b.HasOne("Poyra.Modules.Disputes.Domain.Dispute", null)
                        .WithMany()
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_evidences_disputes_dispute_id");
                });
#pragma warning restore 612, 618
        }
    }
}
