// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.Installments;

#nullable disable

namespace Poyra.Modules.Installments.Migrations
{
    [DbContext(typeof(InstallmentsDbContext))]
    partial class InstallmentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.Installments.Domain.CardBin", b =>
                {
                    b.Property<string>("Bin")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("bin");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("bank_code");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("brand");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("card_type");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasDefaultValue("TR")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCommercial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_commercial");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("program");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Bin")
                        .HasName("pk_card_bins");

                    b.HasIndex("Program")
                        .HasDatabaseName("ix_card_bins_program");

                    b.ToTable("card_bins", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Installments.Domain.InstallmentScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("customer_rate_bps");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("installment_count");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("program");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_installment_schemes");

                    b.HasIndex("TenantId", "ConnectorAccountId", "Program", "InstallmentCount")
                        .IsUnique()
                        .HasDatabaseName("ix_installment_schemes_tenant_id_connector_account_id_program_");

                    b.ToTable("installment_schemes", null, t =>
                        {
                            t.HasCheckConstraint("ck_installment_schemes_count", "installment_count BETWEEN 2 AND 12");

                            t.HasCheckConstraint("ck_installment_schemes_rate", "customer_rate_bps BETWEEN 0 AND 10000");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
