// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.Compliance;

#nullable disable

namespace Poyra.Modules.Compliance.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    [Migration("20260803205729_InitialCompliance")]
    partial class InitialCompliance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.Compliance.Domain.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_audit_log_resource_type_resource_id");

                    b.HasIndex("TenantId", "Actor")
                        .HasDatabaseName("ix_audit_log_tenant_id_actor");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_log_tenant_id_created_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Compliance.Domain.SuspiciousActivityReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_ref");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<string>("PaymentIds")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("payment_ids");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'sar_' || replace(id::text, '-', '')", true);

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("rationale");

                    b.Property<string>("Resolution")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_suspicious_reports");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_suspicious_reports_public_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_suspicious_reports_tenant_id_created_at");

                    b.ToTable("suspicious_reports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
