<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Poyra.SharedKernel\Poyra.SharedKernel.csproj" />
    <ProjectReference Include="..\Poyra.Persistence\Poyra.Persistence.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Tenancy\Poyra.Modules.Tenancy.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Connectors\Poyra.Modules.Connectors.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Routing\Poyra.Modules.Routing.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Webhooks\Poyra.Modules.Webhooks.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Installments\Poyra.Modules.Installments.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Vault\Poyra.Modules.Vault.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Payments\Poyra.Modules.Payments.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Recon\Poyra.Modules.Recon.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Subscriptions\Poyra.Modules.Subscriptions.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.PaymentLinks\Poyra.Modules.PaymentLinks.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Field\Poyra.Modules.Field.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Ledger\Poyra.Modules.Ledger.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Disputes\Poyra.Modules.Disputes.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Risk\Poyra.Modules.Risk.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Compliance\Poyra.Modules.Compliance.csproj" />
    <ProjectReference Include="..\Modules\Poyra.Modules.Customers\Poyra.Modules.Customers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="Npgsql.OpenTelemetry" />
  </ItemGroup>

</Project>
