// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poyra.Modules.Subscriptions;

#nullable disable

namespace Poyra.Modules.Subscriptions.Migrations
{
    [DbContext(typeof(SubscriptionsDbContext))]
    [Migration("20260801181814_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poyra.Modules.Subscriptions.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("interval");

                    b.Property<int>("IntervalCount")
                        .HasColumnType("integer")
                        .HasColumnName("interval_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'pln_' || replace(id::text, '-', '')", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrialDays")
                        .HasColumnType("integer")
                        .HasColumnName("trial_days");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_public_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_plans_tenant_id");

                    b.ToTable("plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_plans_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_plans_interval_count", "interval_count BETWEEN 1 AND 24");

                            t.HasCheckConstraint("ck_plans_trial_days", "trial_days BETWEEN 0 AND 365");
                        });
                });

            modelBuilder.Entity("Poyra.Modules.Subscriptions.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CardToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("card_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<string>("CustomerRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_ref");

                    b.Property<bool>("NeedsCardUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_card_update");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'sub_' || replace(id::text, '-', '')", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("CurrentPeriodEnd")
                        .HasDatabaseName("ix_subscriptions_current_period_end")
                        .HasFilter("status IN ('active','trialing')");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_public_id");

                    b.HasIndex("TenantId", "CustomerRef")
                        .HasDatabaseName("ix_subscriptions_tenant_id_customer_ref");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Subscriptions.Domain.SubscriptionInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastPaymentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_payment_id");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("public_id")
                        .HasComputedColumnSql("'inv_' || replace(id::text, '-', '')", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscription_invoices");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_subscription_invoices_next_retry_at")
                        .HasFilter("status = 'retrying'");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_invoices_public_id");

                    b.HasIndex("SubscriptionId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_invoices_subscription_id_period_start");

                    b.ToTable("subscription_invoices", (string)null);
                });

            modelBuilder.Entity("Poyra.Modules.Subscriptions.Domain.Subscription", b =>
                {
                    b.HasOne("Poyra.Modules.Subscriptions.Domain.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plans_plan_id");
                });

            modelBuilder.Entity("Poyra.Modules.Subscriptions.Domain.SubscriptionInvoice", b =>
                {
                    b.HasOne("Poyra.Modules.Subscriptions.Domain.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_invoices_subscriptions_subscription_id");
                });
#pragma warning restore 612, 618
        }
    }
}
